# Generated by Django 4.0.2 on 2022-07-19 06:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import produit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='static/profil.jpg', upload_to='static')),
                ('description', models.TextField(default='Description de votre boutique')),
                ('note_vendeur', models.DecimalField(decimal_places=1, max_digits=19)),
                ('nbrefollower', models.PositiveIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=produit.models.random_string_generator, unique=True)),
                ('avertissement', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('nbredesactivation', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('active', models.BooleanField(default=False)),
                ('payer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut_commande', models.CharField(blank=True, choices=[('produit en attente de livraison ', 'produit  en attente de livraison'), ('produit en cours de livraison ', 'produit en cours de livraison '), ('produit livré', 'produit  livré')], max_length=100)),
                ('livraison', models.DecimalField(decimal_places=2, max_digits=19)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=19)),
                ('montant_vendeur', models.DecimalField(decimal_places=2, max_digits=19)),
                ('phone_gaalguiMoney', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('recycler', models.BooleanField(default=False)),
                ('annuler', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(max_length=100)),
                ('conversion', models.DecimalField(decimal_places=1, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendu', models.BooleanField(default=False)),
                ('taille', models.CharField(blank=True, max_length=255, null=True)),
                ('couleur', models.CharField(blank=True, max_length=255, null=True)),
                ('qte', models.PositiveIntegerField(default=0)),
                ('variation', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=produit.models.random_string_generator, unique=True)),
                ('recycler', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='static')),
                ('vendu_qte', models.PositiveIntegerField(default=0)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.boutique')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produit.category')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produit.devise')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('vendu', models.BooleanField(default=False)),
                ('qte_vendu', models.PositiveIntegerField(default=0)),
                ('recycler', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
    ]
