# Generated by Django 4.0.2 on 2022-07-19 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('produit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.region'),
        ),
        migrations.AddField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.adress'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produitcommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.cartproduct'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='imageproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.produitimage'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.produit'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cartproduct',
            field=models.ManyToManyField(to='produit.CartProduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='proprietaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boutique',
            name='follower',
            field=models.ManyToManyField(to='produit.Follower'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
