# Generated by Django 4.0.2 on 2022-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='desactiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produitimage',
            name='desactiver',
            field=models.BooleanField(default=False),
        ),
    ]
