# Generated by Django 4.0.2 on 2022-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_produit_desactiver_produitimage_desactiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='codeid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
