# Generated by Django 4.0.2 on 2022-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_produit_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='unite_mesure_poids',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg')], max_length=100),
        ),
    ]
