# Generated by Django 4.0.2 on 2022-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adress_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
